# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 15, 49, 1, 735325), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 15, 49, 1, 734325), editable=False),
        ),
    ]
