# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170515_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 16, 32, 52, 871155), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 16, 32, 52, 871155), editable=False),
        ),
    ]
